#! /bin/bash

# set hostname and hostmap

echo -e " k8s-master \n k8s-node1 \n k8s-node2"
read -p "Choose your host name: " name

hostnamectl set-hostname $name

echo -e "192.168.137.151 k8s-master\n192.168.137.152 k8s-node1\n192.168.137.153 k8s-node2" >> /etc/hosts

hostname
tail -n 3 /etc/hosts
echo "Set Successful"
